export const TURKISH_PROVINCES = [
  "ADANA", "ADIYAMAN", "AFYONKARAHİSAR", "AĞRI", "AKSARAY", "AMASYA", "ANKARA", "ANTALYA",
  "ARDAHAN", "ARTVİN", "AYDIN", "BALIKESİR", "BARTIN", "BATMAN", "BAYBURT", "BİLECİK",
  "BİNGÖL", "BİTLİS", "BOLU", "BURDUR", "BURSA", "ÇANAKKALE", "ÇANKIRI", "ÇORUM",
  "DENİZLİ", "DİYARBAKIR", "DÜZCE", "EDİRNE", "ELAZIĞ", "ERZİNCAN", "ERZURUM", "ESKİŞEHİR",
  "GAZİANTEP", "GİRESUN", "GÜMÜŞHANE", "HAKKARİ", "HATAY", "IĞDIR", "ISPARTA", "İSTANBUL",
  "İZMİR", "KAHRAMANMARAŞ", "KARABÜK", "KARAMAN", "KARS", "KASTAMONU", "KAYSERİ", "KİLİS",
  "KIRIKKALE", "KIRKLARELİ", "KIRŞEHİR", "KOCAELİ", "KONYA", "KÜTAHYA", "MALATYA", "MANİSA",
  "MARDİN", "MERSİN", "MUĞLA", "MUŞ", "NEVŞEHİR", "NİĞDE", "ORDU", "OSMANİYE", "RİZE",
  "SAKARYA", "SAMSUN", "SİİRT", "SİNOP", "ŞANLIURFA", "ŞIRNAK", "SİVAS", "TEKİRDAĞ",
  "TOKAT", "TRABZON", "TUNCELİ", "UŞAK", "VAN", "YALOVA", "YOZGAT", "ZONGULDAK"
].sort((a, b) => a.localeCompare(b, 'tr'));

export const DISTRICTS_BY_PROVINCE: { [key: string]: string[] } = {
  "İSTANBUL": ["Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beykoz", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca", "Çekmeköy", "Esenler", "Esenyurt", "Eyüpsultan", "Fatih", "Gaziosmanpaşa", "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri", "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla", "Ümraniye", "Üsküdar", "Zeytinburnu"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ANKARA": ["Akyurt", "Altındağ", "Ayaş", "Bala", "Beypazarı", "Çamlıdere", "Çankaya", "Çubuk", "Elmadağ", "Etimesgut", "Evren", "Gölbaşı", "Güdül", "Haymana", "Kahramankazan", "Kalecik", "Keçiören", "Kızılcahamam", "Mamak", "Nallıhan", "Polatlı", "Pursaklar", "Sincan", "Şereflikoçhisar", "Yenimahalle"].sort((a, b) => a.localeCompare(b, 'tr')),
  "İZMİR": ["Aliağa", "Balçova", "Bayındır", "Bayraklı", "Bergama", "Beydağ", "Bornova", "Buca", "Çeşme", "Çiğli", "Dikili", "Foça", "Gaziemir", "Güzelbahçe", "Karabağlar", "Karaburun", "Karşıyaka", "Kemalpaşa", "Kınık", "Kiraz", "Konak", "Menderes", "Menemen", "Narlıdere", "Ödemiş", "Seferihisar", "Selçuk", "Tire", "Torbalı", "Urla"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ADANA": ["Aladağ", "Ceyhan", "Çukurova", "Feke", "İmamoğlu", "Karaisalı", "Karataş", "Kozan", "Pozantı", "Saimbeyli", "Sarıçam", "Seyhan", "Tufanbeyli", "Yumurtalık", "Yüreğir"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ANTALYA": ["Akseki", "Aksu", "Alanya", "Demre", "Döşemealtı", "Elmalı", "Finike", "Gazipaşa", "Gündoğmuş", "İbradi", "Kaş", "Kemer", "Kepez", "Konyaaltı", "Korkuteli", "Kumluca", "Manavgat", "Muratpaşa", "Serik"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BURSA": ["Büyükorhan", "Gemlik", "Gürsu", "Harmancık", "İnegöl", "İznik", "Karacabey", "Keles", "Kestel", "Mudanya", "Mustafakemalpaşa", "Nilüfer", "Orhaneli", "Orhangazi", "Osmangazi", "Yenişehir", "Yıldırım"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ADIYAMAN": ["Besni", "Çelikhan", "Gerger", "Gölbaşı", "Kahta", "Merkez", "Samsat", "Sincik", "Tut"].sort((a, b) => a.localeCompare(b, 'tr')),
  "AFYONKARAHİSAR": ["Başmakçı", "Bayat", "Bolvadin", "Çay", "Çobanlar", "Dazkırı", "Dinar", "Emirdağ", "Evciler", "Hocalar", "İhsaniye", "İscehisar", "Kızılören", "Merkez", "Sandıklı", "Sinanpaşa", "Sultandağı", "Şuhut"].sort((a, b) => a.localeCompare(b, 'tr')),
  "AĞRI": ["Diyadin", "Doğubayazıt", "Eleşkirt", "Hamur", "Merkez", "Patnos", "Taşlıçay", "Tutak"].sort((a, b) => a.localeCompare(b, 'tr')),
  "AKSARAY": ["Ağaçören", "Eskil", "Gülağaç", "Güzelyurt", "Merkez", "Ortaköy", "Sarıyahşi", "Sultanhanı"].sort((a, b) => a.localeCompare(b, 'tr')),
  "AMASYA": ["Göynücek", "Gümüşhacıköy", "Hamamözü", "Merkez", "Merzifon", "Suluova", "Taşova"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ARDAHAN": ["Çıldır", "Damal", "Göle", "Hanak", "Merkez", "Posof"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ARTVİN": ["Ardanuç", "Arhavi", "Borçka", "Hopa", "Merkez", "Murgul", "Şavşat", "Yusufeli"].sort((a, b) => a.localeCompare(b, 'tr')),
  "AYDIN": ["Bozdoğan", "Buharkent", "Çine", "Didim", "Efeler", "Germencik", "İncirliova", "Karacasu", "Karpuzlu", "Koçarlı", "Köşk", "Kuşadası", "Kuyucak", "Nazilli", "Söke", "Sultanhisar", "Yenipazar"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BALIKESİR": ["Altıeylül", "Ayvalık", "Balya", "Bandırma", "Bigadiç", "Burhaniye", "Dursunbey", "Edremit", "Erdek", "Gömeç", "Gönen", "Havran", "İvrindi", "Karesi", "Kepsut", "Manyas", "Marmara", "Savaştepe", "Sındırgı", "Susurluk"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BARTIN": ["Amasra", "Kurucaşile", "Merkez", "Ulus"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BATMAN": ["Beşiri", "Gercüş", "Hasankeyf", "Kozluk", "Merkez", "Sason"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BAYBURT": ["Aydıntepe", "Demirözü", "Merkez"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BİLECİK": ["Bozüyük", "Gölpazarı", "İnhisar", "Merkez", "Osmaneli", "Pazaryeri", "Söğüt", "Yenipazar"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BİNGÖL": ["Adaklı", "Genç", "Karlıova", "Kiğı", "Merkez", "Solhan", "Yayladere", "Yedisu"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BİTLİS": ["Adilcevaz", "Ahlat", "Güroymak", "Hizan", "Merkez", "Mutki", "Tatvan"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BOLU": ["Dörtdivan", "Gerede", "Göynük", "Kıbrıscık", "Mengen", "Merkez", "Mudurnu", "Seben", "Yeniçağa"].sort((a, b) => a.localeCompare(b, 'tr')),
  "BURDUR": ["Ağlasun", "Altınyayla", "Bucak", "Çavdır", "Çeltikçi", "Gölhisar", "Karamanlı", "Kemer", "Merkez", "Tefenni", "Yeşilova"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ÇANAKKALE": ["Ayvacık", "Bayramiç", "Biga", "Bozcaada", "Çan", "Eceabat", "Ezine", "Gelibolu", "Gökçeada", "Lapseki", "Merkez", "Yenice"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ÇANKIRI": ["Atkaracalar", "Bayramören", "Çerkeş", "Eldivan", "Ilgaz", "Kızılırmak", "Korgun", "Kurşunlu", "Merkez", "Orta", "Şabanözü", "Yapraklı"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ÇORUM": ["Alaca", "Bayat", "Boğazkale", "Dodurga", "İskilip", "Kargı", "Laçin", "Mecitözü", "Merkez", "Oğuzlar", "Ortaköy", "Osmancık", "Sungurlu", "Uğurludağ"].sort((a, b) => a.localeCompare(b, 'tr')),
  "DENİZLİ": ["Acıpayam", "Babadağ", "Baklan", "Bekilli", "Beyağaç", "Bozkurt", "Buldan", "Çal", "Çameli", "Çardak", "Çivril", "Güney", "Honaz", "Kale", "Merkezefendi", "Pamukkale", "Sarayköy", "Serinhisar", "Tavas"].sort((a, b) => a.localeCompare(b, 'tr')),
  "DİYARBAKIR": ["Bağlar", "Bismil", "Çermik", "Çınar", "Çüngüş", "Dicle", "Eğil", "Ergani", "Hani", "Hazro", "Kayapınar", "Kocaköy", "Kulp", "Lice", "Silvan", "Sur", "Yenişehir"].sort((a, b) => a.localeCompare(b, 'tr')),
  "DÜZCE": ["Akçakoca", "Cumayeri", "Çilimli", "Gölyaka", "Gümüşova", "Kaynaşlı", "Merkez", "Yığılca"].sort((a, b) => a.localeCompare(b, 'tr')),
  "EDİRNE": ["Enez", "Havsa", "İpsala", "Keşan", "Lalapaşa", "Meriç", "Merkez", "Süloğlu", "Uzunköprü"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ELAZIĞ": ["Ağın", "Alacakaya", "Arıcak", "Baskil", "Karakoçan", "Keban", "Kovancılar", "Maden", "Merkez", "Palu", "Sivrice"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ERZİNCAN": ["Çayırlı", "İliç", "Kemah", "Kemaliye", "Merkez", "Otlukbeli", "Refahiye", "Tercan", "Üzümlü"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ERZURUM": ["Aşkale", "Aziziye", "Çat", "Hınıs", "Horasan", "İspir", "Karaçoban", "Karayazı", "Köprüköy", "Narman", "Oltu", "Olur", "Palandöken", "Pasinler", "Pazaryolu", "Şenkaya", "Tekman", "Tortum", "Uzundere", "Yakutiye"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ESKİŞEHİR": ["Alpu", "Beylikova", "Çifteler", "Günyüzü", "Han", "İnönü", "Mahmudiye", "Mihalgazi", "Mihalıççık", "Odunpazarı", "Sarıcakaya", "Seyitgazi", "Sivrihisar", "Tepebaşı"].sort((a, b) => a.localeCompare(b, 'tr')),
  "GAZİANTEP": ["Araban", "İslahiye", "Karkamış", "Nizip", "Nurdağı", "Oğuzeli", "Şahinbey", "Şehitkamil", "Yavuzeli"].sort((a, b) => a.localeCompare(b, 'tr')),
  "GİRESUN": ["Alucra", "Bulancak", "Çamoluk", "Çanakçı", "Dereli", "Doğankent", "Espiye", "Eynesil", "Görele", "Güce", "Keşap", "Merkez", "Piraziz", "Şebinkarahisar", "Tirebolu", "Yağlıdere"].sort((a, b) => a.localeCompare(b, 'tr')),
  "GÜMÜŞHANE": ["Kelkit", "Köse", "Kürtün", "Merkez", "Şiran", "Torul"].sort((a, b) => a.localeCompare(b, 'tr')),
  "HAKKARİ": ["Çukurca", "Merkez", "Şemdinli", "Yüksekova"].sort((a, b) => a.localeCompare(b, 'tr')),
  "HATAY": ["Altınözü", "Antakya", "Arsuz", "Belen", "Defne", "Dörtyol", "Erzin", "Hassa", "İskenderun", "Kırıkhan", "Kumlu", "Payas", "Reyhanlı", "Samandağ", "Yayladağı"].sort((a, b) => a.localeCompare(b, 'tr')),
  "IĞDIR": ["Aralık", "Karakoyunlu", "Merkez", "Tuzluca"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ISPARTA": ["Aksu", "Atabey", "Eğirdir", "Gelendost", "Gönen", "Keçiborlu", "Merkez", "Senirkent", "Sütçüler", "Şarkikaraağaç", "Uluborlu", "Yalvaç", "Yenişarbademli"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KAHRAMANMARAŞ": ["Afşin", "Andırın", "Çağlayancerit", "Dulkadiroğlu", "Ekinözü", "Elbistan", "Göksun", "Nurhak", "Onikişubat", "Pazarcık", "Türkoğlu"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KARABÜK": ["Eflani", "Eskipazar", "Merkez", "Ovacık", "Safranbolu", "Yenice"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KARAMAN": ["Ayrancı", "Başyayla", "Ermenek", "Kazımkarabekir", "Merkez", "Sarıveliler"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KARS": ["Akyaka", "Arpaçay", "Digor", "Kağızman", "Merkez", "Sarıkamış", "Selim", "Susuz"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KASTAMONU": ["Abana", "Ağlı", "Araç", "Azdavay", "Bozkurt", "Cide", "Çatalzeytin", "Daday", "Devrekani", "Doğanyurt", "Hanönü", "İhsangazi", "İnebolu", "Küre", "Merkez", "Pınarbaşı", "Şenpazar", "Seydiler", "Taşköprü", "Tosya"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KAYSERİ": ["Akkışla", "Bünyan", "Develi", "Felahiye", "Hacılar", "İncesu", "Kocasinan", "Melikgazi", "Özvatan", "Pınarbaşı", "Sarıoğlan", "Sarız", "Talas", "Tomarza", "Yahyalı", "Yeşilhisar"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KİLİS": ["Elbeyli", "Merkez", "Musabeyli", "Polateli"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KIRIKKALE": ["Bahşılı", "Balışeyh", "Çelebi", "Delice", "Karakeçili", "Keskin", "Merkez", "Sulakyurt", "Yahşihan"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KIRKLARELİ": ["Babaeski", "Demirköy", "Kofçaz", "Lüleburgaz", "Merkez", "Pehlivanköy", "Pınarhisar", "Vize"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KIRŞEHİR": ["Akçakent", "Akpınar", "Boztepe", "Çiçekdağı", "Kaman", "Merkez", "Mucur"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KOCAELİ": ["Başiskele", "Çayırova", "Darıca", "Derince", "Dilovası", "Gebze", "Gölcük", "İzmit", "Kandıra", "Karamürsel", "Kartepe", "Körfez"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KONYA": ["Ahırlı", "Akören", "Akşehir", "Altınekin", "Beyşehir", "Bozkır", "Cihanbeyli", "Çeltik", "Çumra", "Derbent", "Derebucak", "Doğanhisar", "Emirgazi", "Ereğli", "Güneysınır", "Hadim", "Halkapınar", "Hüyük", "Ilgın", "Kadınhanı", "Karapınar", "Karatay", "Kulu", "Meram", "Sarayönü", "Selçuklu", "Seydişehir", "Taşkent", "Tuzlukçu", "Yalıhüyük", "Yunak"].sort((a, b) => a.localeCompare(b, 'tr')),
  "KÜTAHYA": ["Altıntaş", "Aslanapa", "Çavdarhisar", "Domaniç", "Dumlupınar", "Emet", "Gediz", "Hisarcık", "Merkez", "Pazarlar", "Simav", "Şaphane", "Tavşanlı"].sort((a, b) => a.localeCompare(b, 'tr')),
  "MALATYA": ["Akçadağ", "Arapgir", "Arguvan", "Battalgazi", "Darende", "Doğanşehir", "Doğanyol", "Hekimhan", "Kale", "Kuluncak", "Pütürge", "Yazıhan", "Yeşilyurt"].sort((a, b) => a.localeCompare(b, 'tr')),
  "MANİSA": ["Ahmetli", "Akhisar", "Alaşehir", "Demirci", "Gölmarmara", "Gördes", "Kırkağaç", "Köprübaşı", "Kula", "Salihli", "Sarıgöl", "Saruhanlı", "Selendi", "Soma", "Şehzadeler", "Turgutlu", "Yunusemre"].sort((a, b) => a.localeCompare(b, 'tr')),
  "MARDİN": ["Artuklu", "Dargeçit", "Derik", "Kızıltepe", "Mazıdağı", "Midyat", "Nusaybin", "Ömerli", "Savur", "Yeşilli"].sort((a, b) => a.localeCompare(b, 'tr')),
  "MERSİN": ["Akdeniz", "Anamur", "Aydıncık", "Bozyazı", "Çamlıyayla", "Erdemli", "Gülnar", "Mezitli", "Mut", "Silifke", "Tarsus", "Toroslar", "Yenişehir"].sort((a, b) => a.localeCompare(b, 'tr')),
  "MUĞLA": ["Bodrum", "Dalaman", "Datça", "Fethiye", "Kavaklıdere", "Köyceğiz", "Marmaris", "Menteşe", "Milas", "Ortaca", "Seydikemer", "Ula", "Yatağan"].sort((a, b) => a.localeCompare(b, 'tr')),
  "MUŞ": ["Bulanık", "Hasköy", "Korkut", "Malazgirt", "Merkez", "Varto"].sort((a, b) => a.localeCompare(b, 'tr')),
  "NEVŞEHİR": ["Acıgöl", "Avanos", "Derinkuyu", "Gülşehir", "Hacıbektaş", "Kozaklı", "Merkez", "Ürgüp"].sort((a, b) => a.localeCompare(b, 'tr')),
  "NİĞDE": ["Altunhisar", "Bor", "Çamardı", "Çiftlik", "Merkez", "Ulukışla"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ORDU": ["Akkuş", "Altınordu", "Aybastı", "Çamaş", "Çatalpınar", "Çaybaşı", "Fatsa", "Gölköy", "Gülyalı", "Gürgentepe", "İkizce", "Kabadüz", "Kabataş", "Korgan", "Kumru", "Mesudiye", "Perşembe", "Ulubey", "Ünye"].sort((a, b) => a.localeCompare(b, 'tr')),
  "OSMANİYE": ["Bahçe", "Düziçi", "Hasanbeyli", "Kadirli", "Merkez", "Sumbas", "Toprakkale"].sort((a, b) => a.localeCompare(b, 'tr')),
  "RİZE": ["Ardeşen", "Çamlıhemşin", "Çayeli", "Derepazarı", "Fındıklı", "Güneysu", "Hemşin", "İkizdere", "İyidere", "Kalkandere", "Merkez", "Pazar"].sort((a, b) => a.localeCompare(b, 'tr')),
  "SAKARYA": ["Adapazarı", "Akyazı", "Arifiye", "Erenler", "Ferizli", "Geyve", "Hendek", "Karapürçek", "Karasu", "Kaynarca", "Kocaali", "Pamukova", "Sapanca", "Serdivan", "Söğütlü", "Taraklı"].sort((a, b) => a.localeCompare(b, 'tr')),
  "SAMSUN": ["Alaçam", "Asarcık", "Atakum", "Ayvacık", "Bafra", "Canik", "Çarşamba", "Havza", "İlkadım", "Kavak", "Ladik", "Ondokuzmayıs", "Salıpazarı", "Tekkeköy", "Terme", "Vezirköprü", "Yakakent"].sort((a, b) => a.localeCompare(b, 'tr')),
  "SİİRT": ["Baykan", "Eruh", "Kurtalan", "Merkez", "Pervari", "Şirvan", "Tillo"].sort((a, b) => a.localeCompare(b, 'tr')),
  "SİNOP": ["Ayancık", "Boyabat", "Dikmen", "Durağan", "Erfelek", "Gerze", "Merkez", "Saraydüzü", "Türkeli"].sort((a, b) => a.localeCompare(b, 'tr')),
  "SİVAS": ["Akıncılar", "Altınyayla", "Divriği", "Doğanşar", "Gemerek", "Gölova", "Hafik", "İmranlı", "Kangal", "Koyulhisar", "Merkez", "Suşehri", "Şarkışla", "Ulaş", "Yıldızeli", "Zara"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ŞANLIURFA": ["Akçakale", "Birecik", "Bozova", "Ceylanpınar", "Eyyübiye", "Halfeti", "Haliliye", "Harran", "Hilvan", "Karaköprü", "Siverek", "Suruç", "Viranşehir"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ŞIRNAK": ["Beytüşşebap", "Cizre", "Güçlükonak", "İdil", "Merkez", "Silopi", "Uludere"].sort((a, b) => a.localeCompare(b, 'tr')),
  "TEKİRDAĞ": ["Çerkezköy", "Çorlu", "Ergene", "Hayrabolu", "Kapaklı", "Malkara", "Marmaraereğlisi", "Muratlı", "Saray", "Şarköy", "Süleymanpaşa"].sort((a, b) => a.localeCompare(b, 'tr')),
  "TOKAT": ["Almus", "Artova", "Başçiftlik", "Erbaa", "Merkez", "Niksar", "Pazar", "Reşadiye", "Sulusaray", "Turhal", "Yeşilyurt", "Zile"].sort((a, b) => a.localeCompare(b, 'tr')),
  "TRABZON": ["Akçaabat", "Araklı", "Arsin", "Beşikdüzü", "Çarşıbaşı", "Çaykara", "Dernekpazarı", "Düzköy", "Hayrat", "Köprübaşı", "Maçka", "Of", "Ortahisar", "Sürmene", "Şalpazarı", "Tonya", "Vakfıkebir", "Yomra"].sort((a, b) => a.localeCompare(b, 'tr')),
  "TUNCELİ": ["Çemişgezek", "Hozat", "Mazgirt", "Merkez", "Nazımiye", "Ovacık", "Pertek", "Pülümür"].sort((a, b) => a.localeCompare(b, 'tr')),
  "UŞAK": ["Banaz", "Eşme", "Karahallı", "Merkez", "Sivaslı", "Ulubey"].sort((a, b) => a.localeCompare(b, 'tr')),
  "VAN": ["Bahçesaray", "Başkale", "Çaldıran", "Çatak", "Edremit", "Erciş", "Gevaş", "Gürpınar", "İpekyolu", "Muradiye", "Özalp", "Saray", "Tuşba"].sort((a, b) => a.localeCompare(b, 'tr')),
  "YALOVA": ["Altınova", "Armutlu", "Çınarcık", "Çiftlikköy", "Merkez", "Termal"].sort((a, b) => a.localeCompare(b, 'tr')),
  "YOZGAT": ["Akdağmadeni", "Aydıncık", "Boğazlıyan", "Çandır", "Çayıralan", "Çekerek", "Kadışehri", "Merkez", "Saraykent", "Sarıkaya", "Sorgun", "Şefaatli", "Yenifakılı", "Yerköy"].sort((a, b) => a.localeCompare(b, 'tr')),
  "ZONGULDAK": ["Alaplı", "Çaycuma", "Devrek", "Ereğli", "Gökçebey", "Kilimli", "Kozlu", "Merkez"].sort((a, b) => a.localeCompare(b, 'tr')),
};

// For provinces not in the detailed list, return empty array
export const getDistrictsByProvince = (province: string): string[] => {
  return DISTRICTS_BY_PROVINCE[province] || [];
};
